name: Run Lua Testing

on: [push, pull_request]

jobs:
  busted:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lua Busted
        uses: lunarmodules/busted@v2.2.0

