name: Run Lua Testing
on: [push, pull_request]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: luarocks
        uses: leafo/gh-actions-luarocks@v4
      - name: run test
        shell: bash
        run: |
          luarocks install luacheck
          luarocks install vusted
          vusted ./test
